### ISSUE TITLE
can we make the dispatch globally? 

### ISSUE THREAD

**Issue by aaronkzhou** [BigAB/use-epic#23]
**Is your feature request related to a problem? Please describe.**

scenario: 
I wanna dispatch different actions from different Epic.
```
const [, dispatchLogin] = useEpic(loginEpic)
const [, dispatchActivate] = useEpic(activateEpic)

dispatchActivate({type1,payload1})
dispatchLogin({type1,payload1})

above are different dispatch, and cannot be access and catch globally
```

**Describe the solution you'd like**

```
combine all the epics and use single dispatch like `redux-observable` combineEpics
```

**Describe alternatives you've considered**

**Additional context**

**Comment by BigAB** [comment]
I don't think I want to dispatch globally, you could probably use the "deps" to pass a function to all the epics that you use for globally handling errors. 
You could probably wrap epics in a function that pipes all actions to some global observable (or function or whatever) with something like `const myEpic = createEpic((action$, state$) => ...)`.

It may be more appropriate to use [redux-observable](https://redux-observable.js.org/) if you want that kind of behavior though.
